version: "3"

networks:
    web:
        external: true

services:
    platform:
        image:  0x12f/platform:latest
        environment:
            - DEBUG=1
          # - SALT=Please-Change-Me
          # - SIMPLE_PHONE_CHECK=1
          # - DATABASE=mysql://user:secret@localhost/mydb
          # - SENTRY=""
        volumes:
            - ./plugin:/var/container/plugin:ro
            - ./resource:/var/container/public/resource:ro
            - ./theme:/var/container/theme:rw
            - ./var:/var/container/var:rw
            - ./var/upload:/var/container/public/uploads:rw
        labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.backend=example.site.0x12f.com
            - traefik.frontend.rule=Host:example.site.0x12f.com
        #   - traefik.frontend.redirect.entryPoint=https
            - traefik.docker.network=web
        networks:
            - web
