version: "3"

networks:
    web:
        external: true

services:
    platform:
        image: ghcr.io/getwebspace/platform:master
        environment:
            - DEBUG=1
          # - SIMPLE_PHONE_CHECK=1
          # - DATABASE=mysql://user:secret@localhost/mydb
        volumes:
            - ./plugin:/var/container/plugin:ro
            - ./resource:/var/container/public/resource:ro
            - ./theme:/var/container/theme:rw
            - ./var:/var/container/var:rw
            - ./var/upload:/var/container/public/uploads:rw
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.example.entrypoints=http,https"
            - "traefik.http.routers.example.tls=true"
            - "traefik.http.routers.example.tls.certresolver=letsEncrypt"
            - "traefik.http.routers.example.rule=Host(`example.com`)"
            - "traefik.http.services.example-service.loadbalancer.server.port=80"
        networks:
            - web
