version: '3'
networks:
    web:
        external: true
    internal:
        external: false
services:
    php:
        build:
            context: docker/php
        container_name: phpworker
        working_dir: /var/www
        command: php -S 0.0.0.0:9000 -t public
        environment:
            docker: "true"
        volumes:
            - $PWD/engine/app:/var/www/app:ro
            - $PWD/engine/config:/var/www/config:ro
            - $PWD/engine/public:/var/www/public:ro
            - $PWD/engine/src:/var/www/src:ro
            - $PWD/resource:/var/www/public/resource:ro
            - $PWD/theme:/var/www/theme:ro
            - $PWD/var:/var/www/var:rw
            - $PWD/var/upload:/var/www/public/uploads:rw
            - $PWD/engine/vendor:/var/www/vendor:ro
        labels:
            - traefik.enable=true
            - traefik.backend=nails-salon.site.0x12f.com
            - traefik.frontend.rule=Host:nails-salon.site.0x12f.com
        #   - traefik.frontend.redirect.entryPoint=https
            - traefik.docker.network=web
        networks:
            - internal
            - web
    cache:
        image: redis:4-alpine
        container_name: redisworker
        networks:
            - internal
        labels:
            - traefik.enable=false
