version: '2'
networks:
    web:
        external: true
    internal:
        external: false
services:
    php:
        build:
            context: docker/php
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        volumes:
            - $PWD/engine:/var/www:ro
            - $PWD/engine/var:/var/www/var:rw
            - $PWD/theme:/var/www/theme/docker:rw
        labels:
            - traefik.backend=0x12f
            - traefik.frontend.rule=Host:test.site.0x12f.com
            - traefik.docker.network=web
            - traefik.port=8080
        networks:
            - internal
            - web
    cache:
        image: redis:4-alpine
        networks:
            - internal
        labels:
            - traefik.enable=false
