version: '2'
networks:
    web:
        external: true
    internal:
        external: false
services:
    php:
        build:
            context: docker/php
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        volumes:
            - $PWD/engine/app:/var/www/app:ro
            - $PWD/engine/config:/var/www/config:ro
            - $PWD/engine/public:/var/www/public:ro
            - $PWD/engine/src:/var/www/src:ro
            - $PWD/resource:/var/www/public/resource:ro
            - $PWD/theme:/var/www/theme:ro
            - $PWD/var:/var/www/var:rw
            - $PWD/var/upload:/var/www/public/uploads:rw
            - $PWD/engine/vendor:/var/www/vendor:ro
        labels:
            - traefik.backend=0x12f.test
            - traefik.frontend.rule=Host:test.site.0x12f.com
            - traefik.docker.network=web
            - traefik.port=8080
        networks:
            - internal
            - web
    cache:
        image: redis:4-alpine
        networks:
            - internal
        labels:
            - traefik.enable=false
