version: '3'
networks:
    lan:
        external: false
    web:
        external: true
services:
    php:
        image: 0x12f/php:latest
        environment:
            docker: "true"
        volumes:
            - $PWD/engine/app:/var/container/app:ro
            - $PWD/engine/config:/var/container/config:ro
            - $PWD/engine/public:/var/container/public:ro
            - $PWD/engine/src:/var/container/src:ro
            - $PWD/resource:/var/container/public/resource:ro
            - $PWD/theme:/var/container/theme:ro
            - $PWD/var:/var/container/var:rw
            - $PWD/var/upload:/var/container/public/uploads:rw
            - $PWD/engine/vendor:/var/container/vendor:ro
        labels:
            - traefik.enable=false
        networks:
            - lan
            - web

    web:
        image: nginx:alpine
        volumes:
            - $PWD/engine/app:/var/container/app:ro
            - $PWD/engine/config:/var/container/config:ro
            - $PWD/engine/public:/var/container/public:ro
            - $PWD/engine/src:/var/container/src:ro
            - $PWD/resource:/var/container/public/resource:ro
            - $PWD/theme:/var/container/theme:ro
            - $PWD/var:/var/container/var:rw
            - $PWD/var/upload:/var/container/public/uploads:rw
            - $PWD/engine/vendor:/var/container/vendor:ro
            - $PWD/nginx.conf:/etc/nginx/nginx.conf:ro
            - $PWD/var/log/nginx:/var/log/nginx
        labels:
            - traefik.enable=true
            - traefik.backend=example.site.0x12f.com
            - traefik.frontend.rule=Host:example.site.0x12f.com
          # - traefik.frontend.redirect.entryPoint=https
            - traefik.docker.network=web
        networks:
            - lan
            - web

    cache:
        image: redis:4-alpine
        restart: always
        labels:
            - traefik.enable=false
        networks:
            - lan
